repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        exclude: 'tools/|(pypinyin/(legacy/|phonetic_symbol.py))'
      - id: double-quote-string-fixer
        exclude: 'pypinyin/(legacy/|phonetic_symbol.py)'
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg|.*.json'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: 'tools|pypinyin/(legacy/|phonetic_symbol.py)|(docs/conf.py)'
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.812'
  #   hooks:
  #     - id: mypy
  #       files: 'pypinyin/'
